### ISSUE TITLE
No CLS or SEP token in the batches

### ISSUE THREAD

**Issue by wanderingashenvalewisp** [LightTag/sequence-labeling-with-transformers#2]
Hi LightTag,

thanks for the tutorial :) 
I was wondering whether there is a specific reason for not including the special tokens when [tokenizing the data](https://github.com/LightTag/sequence-labeling-with-transformers/blob/e9f205db69b08b8543220221b29f1c775cc7270f/sequence_aligner/dataset.py#L39)? 
They are not getting added either to the batches later on before training the model.

kind regards,
wanderingashenvalewisp

**Comment by talolard** [comment]
Hi, good question!
Our implementation is optimized for "text in the wild" and assumes texts are long. So we [window](https://github.com/LightTag/sequence-labeling-with-transformers/blob/e9f205db69b08b8543220221b29f1c775cc7270f/sequence_aligner/dataset.py#L56) over them. Because of the windowing having a start token doesn't make sense because the first token in a window isn't really the start of anything. 

We weren't sure where the SEP token comes from, e.g. do tokenizers split sentences automatically. Since we're windowing and we might cut a sentence somewhere SEPs don't make sense either. 

Both of these rationales are subjective, so try with or without and test if it makes a difference for your use case

**Comment by wanderingashenvalewisp** [comment]
Ah, I see. 
Thanks alot for the answer :) 
Go LightTag! 

// wanderingashenvalewisp
